### ISSUE TITLE
Add .NET analysis rules

### ISSUE THREAD

**Issue by BjarkeMeier** [Energinet-DataHub/opengeh-wholesale#1016]
### Synopsis
As a system owner
I want relevant .NET analysis rules enabled
So that the system becomes more maintainable and reliable

### Acceptance-Criteria
- [ ] The rules the developers find beneficial have been implemented in builds in pipelines

### Tech Notes
This story originates from a [globalization error in the wholesale domain](https://app.zenhub.com/workspaces/mandalorian-5fd22a1a59e4740018f5ab5a/issues/gh/energinet-datahub/opengeh-wholesale/730) and the solution to activate .NET globalization analysis rules was agreed upon as a suitable solution at an arch guild meeting. It was also agreed upon that it would make sense to check for other relevant rules at the same time.

**Comment by MadsBloendAndersen** [comment]
@BjarkeMeier keep this or #730?

**Comment by BjarkeMeier** [comment]
They both make sense. Alternatively, #730 can be rewritten to include #1016.
