### ISSUE TITLE
[Hackathon] What is the potential of the Databricks VSCode extension?

### ISSUE THREAD

**Issue by BjarkeMeier** [Energinet-DataHub/opengeh-wholesale#1017]
### Synopsis
As a developer
I want to investigate the new Databricks VSCode extension
So that I can determine whether it has the potential to increase productivity and/or DX

### Tech. Notes
https://docs.databricks.com/dev-tools/vscode-ext.html

**Comment by johevemi** [comment]
I have invited the backenders to a meeting where we will determine whether or not we will pursue the Databricks vscode extension in form of a hackathon
