### ISSUE TITLE
Calculate negative grid loss and add it to production

### ISSUE THREAD

**Issue by johevemi** [Energinet-DataHub/opengeh-wholesale#1054]
### Synopsis 
As datahub, I want to calculate negative grid loss
so I can add them to production

### AC

- [ ] When a batch has finished Then production result will be included in negative grid loss (with a positive sign).
- [ ] The aggregated production per energy supplier can be equal to the calculated negative grid loss (with a positive sign) if the energy supplier has only the system correction metering point in the grid area.
- [ ] PO/SME can verify the results with the help of a developer
- [ ] The adjusted production is published for the specific energy supplier registered on the system correction metering point. 

### Tech note

Notes:
We need to find out how we get information about which energy supplier is responsible for grid loss in a grid area at a given time

**Comment by khatozen** [comment]
Tested OK, this issue can be closed,
See the test result bellow:
![image.png](https://images.zenhubusercontent.com/6110f1589f04be24392a986f/94c53671-fbc2-4290-b942-120eb574886e)
