### ISSUE TITLE
Calculate positive grid loss and add to flex consumption

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/opengeh-wholesale#1125]
### Synpsis 
As datahub I want to calculate positve grid loss
so I can add them to flex consumption

### AC

- [ ] When a batch has finished Then flex consumption result will be included negative grid loss for all actors.
- [ ] PO/SME can verify the results through data bricks
- [ ] The adjusted flex consumption is published for the specific energy supplier that is registered on the grid loss metering point. 
- [ ] Calculate total consumption (Net_exchange per grid area + Production per grid area) and publish results to EDI
- [ ] Calculate residual consumption (Step 22) (Total consumption per grid area - (non-profiled consumption per grid area + flex consumption per grid area))

### Tech note

Notes:
We need to find out how we get information about which energy supplier is responsible for grid loss in a grid area at a given time

**Comment by khatozen** [comment]
Tested OK
In the following table you can se the test result, when comparing the calculated data from PRE07 and DH3:
![image.png](https://images.zenhubusercontent.com/6110f1589f04be24392a986f/8cb89dbc-7965-465b-b156-bc78f2003768)
