### ISSUE TITLE
Settlement reports must only include data from fully completed calculations

### ISSUE THREAD

**Issue by JesperGomes** [Energinet-DataHub/opengeh-wholesale#1214]
### Synopsis
_____________
As an actor
I only want my settlement reports to include data from calculations that have succesfully completed
so that I only download valid data

### Acceptance Criteria
________________
- [ ] Calculations that failed or were cancelled will be excluded from the settlement report
- [ ] If results were saved succesfully but basis data was not (or vice versa), the data will not be part of the report

### Tech. Notes
________________

### Task List
_________________
#### Tasks in Development
_________________
#### Tasks Completed
_________________

**Comment by khatozen** [comment]
This will be resolved in feature https://github.com/Energinet-DataHub/green-energy-hub/issues/561#issue-2092572600
