### ISSUE TITLE
TECH: Replace DbUp with AMI compliant solution

### ISSUE THREAD

**Issue by BjarkeMeier** [Energinet-DataHub/opengeh-wholesale#1232]
Required by Outlaws in order to be able to create a production environment.

BJM, status 6/7-2023:
Titans are working on a tool/solution for migrating SQL server databases using plain SQL script files. They will work together with Søren and Dan on the requirements. It is anticipated that when done Mandalorian should be able to quickly and easily transition from DbUp to this new tool.
The story is blocked until the new tool is available.

**Comment by MadsBloendAndersen** [comment]
@BjarkeMeier could you please refine this ****

**Comment by BjarkeMeier** [comment]
No longer blocked. See https://energinet.atlassian.net/wiki/spaces/D3/pages/525467680/Migrating+from+DbUp.Reboot+back+to+DbUp

**Comment by BjarkeMeier** [comment]
Outlaws er informeret om opdateringen.
