### ISSUE TITLE
Hide wholesale menu items in DH3 in production environments

### ISSUE THREAD

**Issue by PerTHenriksen** [Energinet-DataHub/opengeh-wholesale#128]
As an it vendor, 
I am not interested in having access to starting aggregation process, 
so im not unnecessarily confused about menu points in GUI. 

FAS users start all batch jobs in DH3, so functionality are therefore irrelevant for IT vendors or market actors. This issue will be replaced by user management. 

*Tech note.
In collaboration with Mighty Ducks , please enable feature flagging for the start aggregation process, so that the functionality is only accessable on T and U environment. as it is solely a Datahub FAS functionality, and intended for them to use.

Dev note:
From the feature flag documentation: `Feature flags are not supposed to live long; therefore, they have a maximum lifetime of 14 days (If a feature flag is older than 14 days, an automated test will fail).`

If implemented in current state, we will need a manual process every sprint to maintain the flag. Is this ok? If yes, a draft PR: https://github.com/Energinet-DataHub/greenforce-frontend/pull/742

**Comment by MadsBloendAndersen** [comment]
@BjarkeMeier Is this story relevant for the connected feature?

**Comment by BjarkeMeier** [comment]
Yes, it was discussed with @PerTHenriksen, and the solution with Morten K as well.

**Comment by MadsBloendAndersen** [comment]
@BjarkeMeier + @ftoft  will refine

**Comment by BjarkeMeier** [comment]
@MadsBloendAndersen, we're done with the refinement. We're not sure about the value proposition. Can you update/write the user story?

**Comment by MadsBloendAndersen** [comment]
@BjarkeMeier udpated

**Comment by defectiveAi** [comment]
Reference to Texas Rangers feature request: https://app.zenhub.com/workspaces/mighty-ducks---texas-rangers-61941fea47ab810010e9aa91/issues/energinet-datahub/greenforce-frontend/771

**Comment by lasrinnil** [comment]
U001
![image.png](https://images.zenhubusercontent.com/60bdfcb3effb2082025638c1/4e067a67-ba7a-48e6-965a-d5d749388076)

T001
![image.png](https://images.zenhubusercontent.com/60bdfcb3effb2082025638c1/69451ccd-dc1f-4891-8364-6406c7ade9d2)

B001
![image.png](https://images.zenhubusercontent.com/60bdfcb3effb2082025638c1/3cbb86dd-1de8-42a3-9783-1a3cb6cf0b70)
