### ISSUE TITLE
Use the SQL database to find the latest batches, and then use that to query latest results for settlement reports

### ISSUE THREAD

**Issue by JesperGomes** [Energinet-DataHub/opengeh-wholesale#1333]
As a developer I want to
refactor the code that creates Databricks SQL statements for settlement reports
so that I reduce the risk of introducing bugs without knowing it

**Technical notes:**
From the SQL database, lookup which batches (with associated periods and grid areas)  we need in order to get the latest data for settlement reports. We can build the query string with this information and thereby avoid the self-join of the table (see notes in the picture below).

This approach will further enable us to:
1) only query data for which the batch has successfully finalized (this is in fact most likely a bug in the system right now).
2) extend the code later so also evaluate version information of the data based on the database query.

![b85ccdb9-c9ee-4fc4-be7b-24d0d4c32c7f](https://github.com/Energinet-DataHub/opengeh-wholesale/assets/112619721/925904db-051d-4e16-8838-d6090d0b8278)

**Comment by BjarkeMeier** [comment]
@JesperGomes and @MadsBloendAndersen isn't this related to versioning and should be turned into a business story?

**Comment by khatozen** [comment]
This will be resolved in feature https://github.com/Energinet-DataHub/green-energy-hub/issues/561#issue-2092572600
