### ISSUE TITLE
Make all options deferred loaded

### ISSUE THREAD

**Issue by JesperGomes** [Energinet-DataHub/opengeh-wholesale#1337]
Some options are currently immediate loaded (see for example in https://github.com/Energinet-DataHub/opengeh-wholesale/blob/main/source/dotnet/wholesale-api/WebApi/Configuration/ModulesRegistration.cs).

All options should be deferred loaded as explained here:
https://app.zenhub.com/workspaces/mandalorian-5fd22a1a59e4740018f5ab5a/issues/gh/energinet-datahub/opengeh-wholesale/934

**Comment by BjarkeMeier** [comment]
@dstenroejl would you mind helping us refine this story?
