### ISSUE TITLE
[Investigate] Support open-ended charges

### ISSUE THREAD

**Issue by Sondergaard** [Energinet-DataHub/opengeh-wholesale#1451]
## Description

As an architect
I would like feedback on possible scenarios for supporting open-ended and finite charges
So that I can make a decision that benefits the overall system

## Scope

Only consider impact for Wholesale
Deadline: 2023-09-29

## Acceptance criteria

- [ ] Explore different scenarios including solution no. 2
- [ ] Each relevant scenario has been evaluated with pros and cons
- [ ] Result of analysis is presented to architects and POs (MND, PTH)

## Suggested scenarios

- A model where wholesale supports both open-ended and finte charge model concurrently
- Support open-ended and in phase 3 only support finite model
- Make conversion in wholesale on-the-fly

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdS9JIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5c9a8eb6afcb4a3fe55cf3752336692ef973af7d/image.png)

**Comment by BjarkeMeier** [comment]
My subjective impression from todays meeting between Mandalorian and Volt:
- There are no (significant) benefits of transforming (exIX to CIM) in wholesale
- Transforming in wholesale has the cons: It is Volt who has most relevant experience and knowledge, and transforming in wholesale (at least if done during calculation) will affect performance of calculations
- Solution 2 wasn't really discussed

I gave the following personal subjective impressions to the architects afterwards (during a talk about possibilities)
- It will probably be more expensive to switch to ebIX in the calculations
- It will probably be much more expensive to update calculations to CIM in phase 3
- So, it's a matter of whether this added cost can be either justified or compensated by larger cost reductions in the migrations domain

**Comment by BjarkeMeier** [comment]
Jeg har rakt ud til arkitekterne om de ønsker mere. Jeg mener, at man godt kan hævde, at AC'erne er opfyldt.
Jeg anbefaler, at vi lukker storien, hvis ikke de vender tilbage.
