### ISSUE TITLE
Automatically restart processes  that was terminated by deployment

### ISSUE THREAD

**Issue by lasrinnil** [Energinet-DataHub/opengeh-wholesale#159]
Synopsis
----------------
As a user
I want to be sure that processes that are terminated by a new code deployment will be restarted
So that we can be sure that processes will run when ordered to.

Acceptance-Criteria
----------------
- [ ] Processes that are terminated when new code is deployed, are rerun when new jobs are deployed.

Tech notes
------------
Research if DataBricks itself has someway to configure to try to rerun terminated jobs
 
This will not affect streaming jobs (ingestion of integration events and time series) since streaming jobs restart automatically when redeployed

Tasks
-----------------
- [X] Processes that are terminated when new code is deployed, are rerun when new jobs are deployed.
- [x] Integration tests

**Comment by MadsBloendAndersen** [comment]
@lasrinnil will set up a meeting regarding this topic

**Comment by lasrinnil** [comment]
After attempting to recreate the scenario with deploying code when the jobs are running and expecting them to cancle. This was not the case, so this issue will be closed when the code to handle the retry of canceled jobs is removed.
