### ISSUE TITLE
Remove CalculatedResultCompleted when Mosaic has implemented EnergyResultProducedV2

### ISSUE THREAD

**Issue by energinet-ajw** [Energinet-DataHub/opengeh-wholesale#1617]
In .NET remove logic and tests related to CalculatedResultCompleted.
This includes files and folders in:

The project Events.Infrastructure in the folder /IntegrationEvents.
The test projects.
The contracts project.

**Comment by BjarkeMeier** [comment]
Soleved by @JesperGomes
