### ISSUE TITLE
Clean up secrets.json

### ISSUE THREAD

**Issue by energinet-ajw** [Energinet-DataHub/opengeh-wholesale#1644]
As a developer 
I would like a up-to-date secrets.json file that reflect the current environment 
so I can spin up the Wholesale API for testing/debugging purposes.

Tasks:
-[ ] Update the secrets.json file with the correct values in order to spin up the Wholesale API
-[ ] Commit the changes to dh3-dev-secrets (see dh3-dev-secrets\opengeh-wholesale\apps\WebApi\)
-[ ] Update the documentation on Conflucene if needed (see https://energinet.atlassian.net/wiki/spaces/D3/pages/562397227/Executing+Locally)

-[ ] Change the setting SERVICE_BUS_MANAGE_CONNECTION_STRING so we have a LISTEN and a SEND setting (or a combined setting).
The important thing is that we don't want a MANAGE permisson.

**Comment by BjarkeMeier** [comment]
Find it in the secrets repo.
Dan will create a separate story to stop using the service bus managed connection string.
