### ISSUE TITLE
Tech-debt: Fix skipped tests

### ISSUE THREAD

**Issue by BjarkeMeier** [Energinet-DataHub/opengeh-wholesale#173]
Status of #31 by Alex in teams:

3) Opgave #31 er done og er i Testing. Bemærk, at der ikke er mulighed for at integrationsteste DataLake storage, så det kan være vi bliver nødt til at bede MD om at udvide TestCommon. Indtil da er der sat Skip på i Sender.

**Comment by MadsBloendAndersen** [comment]
@lasrinnil + @BjarkeMeier will combine #173 and #109

**Comment by BjarkeMeier** [comment]
Moving content to #109, which will be refined afterward.
