### ISSUE TITLE
Peek/Dequeue RSM-14 with proper <version>

### ISSUE THREAD

**Issue by PerTHenriksen** [Energinet-DataHub/opengeh-wholesale#174]
Synopsis
As an MDR
I want to be able to differentiate between different runs for the same day, grid area and process
So that market actors know how many times a period has been rerun.

Acceptance-Criteria
- [ ] The version number of RSM-014 series is incremented for each re-run for the same day and grid area balance fixing.
Tech-Notes

- [ ] The version number in RSM-014 message only increments upon successful runs

- [ ] test scenarioes

Description for field:
The version number is unique per grid area, day and aggregation. Re-running the balance fixing, wholesale fixing or correction settlement for a period will increment the version numbers for each of the affected days. 

```
 <cim:Series>
        <cim:mRID>79499109-a414-4e96-a5f8-231885788ff0</cim:mRID>
 -->    <cim:version>1</cim:version>
        <cim:marketEvaluationPoint.type>E18</cim:marketEvaluationPoint.type>
        <cim:meteringGridArea_Domain.mRID codingScheme="NDK">806</cim:meteringGridArea_Domain.mRID>
        <cim:product>8716867000030</cim:product>
        <cim:quantity_Measure_Unit.name>KWH</cim:quantity_Measure_Unit.name>

```

The following representation shows how version number is determined in an RSM-014 forwarded to MDR when completing a balance fixing process: 
![image.png](https://images.zenhubusercontent.com/60d0699cbe9e2f6f18493e89/8a9467f8-fe16-4c65-8c4c-2379576ada2f)

**Comment by MadsBloendAndersen** [comment]
@lasrinnil I've added a representation of the logic we were talking about earlier, regarding version number in RSM-014 messages.
