### ISSUE TITLE
Bug: Error receiving market participant integration events

### ISSUE THREAD

**Issue by BjarkeMeier** [Energinet-DataHub/opengeh-wholesale#205]
### Observation

Errors are logged in b-001.

Example [here](https://portal.azure.com/#view/AppInsightsExtension/DetailsV2Blade/ComponentId~/%7B%22SubscriptionId%22%3A%220f12dae0-3f9d-46ae-93a7-7091ff0b950d%22%2C%22ResourceGroup%22%3A%22rg-DataHub-SharedResouces-B-002%22%2C%22Name%22%3A%22appi-shared-sharedres-b-002%22%2C%22LinkedApplicationType%22%3A0%2C%22ResourceId%22%3A%22%252Fsubscriptions%252F0f12dae0-3f9d-46ae-93a7-7091ff0b950d%252FresourceGroups%252Frg-DataHub-SharedResouces-B-002%252Fproviders%252FMicrosoft.Insights%252Fcomponents%252Fappi-shared-sharedres-b-002%22%2C%22ResourceType%22%3A%22microsoft.insights%252Fcomponents%22%2C%22IsAzureFirst%22%3Afalse%7D/DataModel~/%7B%22eventId%22%3A%22828e8390-17c5-11ed-90e0-000d3aac8608%22%2C%22timestamp%22%3A%222022-08-09T09%3A26%3A58.304Z%22%2C%22cacheId%22%3A%222a4fb63b-594c-4330-b1ec-21190f3acb1b%22%2C%22eventTable%22%3A%22exceptions%22%2C%22timeContext%22%3A%7B%22durationMs%22%3A86400000%2C%22endTime%22%3A%222022-08-10T08%3A11%3A17.761Z%22%7D%7D):

![image.png](https://images.zenhubusercontent.com/60c2e712ae37899de9483e3a/772c2f30-689e-4daa-9586-426b8277728e)

### Comments

The anticipation is that the NuGet package is outdated and thus fails to parse new events. PR #204 updates to the latest version of the NuGet package.

I have reached out to @FirestarJes of team Titans to ask for a more helpful error message. Perhaps we also need a project-level talk about how to prevent this kind of problem in the future.

Is it good enough to discover missed integration events by manually inspecting app insights transaction log (I believe not)?

Should we monitor dead letters actively/automatically?

**Comment by BjarkeMeier** [comment]
Talked to @FirestarJes from team Titans. The anticipation is that the problem is "on their side". We're awaiting team Titans.

**Comment by BjarkeMeier** [comment]
@MadsBloendAndersen, @lasrinnil, and I recommend closing this bug. We originally observed some logged errors. We haven't verified that we've lost any data. Titans have updated their package, which seems to have solved the problem. Feel free to reach out if you have comments or want further investigation or actions.

**Comment by MadsBloendAndersen** [comment]
@BjarkeMeier @lasrinnil Maybe I'll have more question when we start the flow test, from creating metering points to starting a process. But for right now, i don't see how this bug affects me, so if you recommend to close it, lets do that.

**Comment by lasrinnil** [comment]
Closing in accordance with @MadsBloendAndersen
