### ISSUE TITLE
Bug: Periodic errors connecting to SQL database

### ISSUE THREAD

**Issue by BjarkeMeier** [Energinet-DataHub/opengeh-wholesale#206]
### Observation

Errors about database connectivity in b-002.  Example [here](https://portal.azure.com/#view/AppInsightsExtension/DetailsV2Blade/ComponentId~/%7B%22SubscriptionId%22%3A%220f12dae0-3f9d-46ae-93a7-7091ff0b950d%22%2C%22ResourceGroup%22%3A%22rg-DataHub-SharedResouces-B-002%22%2C%22Name%22%3A%22appi-shared-sharedres-b-002%22%2C%22LinkedApplicationType%22%3A0%2C%22ResourceId%22%3A%22%252Fsubscriptions%252F0f12dae0-3f9d-46ae-93a7-7091ff0b950d%252FresourceGroups%252Frg-DataHub-SharedResouces-B-002%252Fproviders%252FMicrosoft.Insights%252Fcomponents%252Fappi-shared-sharedres-b-002%22%2C%22ResourceType%22%3A%22microsoft.insights%252Fcomponents%22%2C%22IsAzureFirst%22%3Afalse%7D/DataModel~/%7B%22eventId%22%3A%2225573f97-16fd-11ed-90e0-000d3aaba7b4%22%2C%22timestamp%22%3A%222022-08-08T09%3A32%3A19.296Z%22%2C%22cacheId%22%3A%2201973dd8-b080-45e7-83fc-29e0a03ed926%22%2C%22eventTable%22%3A%22exceptions%22%2C%22timeContext%22%3A%7B%22durationMs%22%3A86400000%2C%22endTime%22%3A%222022-08-08T10%3A30%3A41.363Z%22%7D%7D)

![image](https://user-images.githubusercontent.com/11583438/183400868-a4d8bdc5-17cd-4aa3-92af-961b5d01814f.png)

### Comments

The errors hint at [this solution](https://docs.microsoft.com/en-us/ef/core/miscellaneous/connection-resiliency).

The recommendation has been implemented in PR #196.

### Test

It's probably not possible to directly test the solution. I recommend accepting the code change as the solution and rely on future monitoring to suggest whether the recilliency has been improved.

**Comment by ftoft** [comment]
Its looks fine. Only finding is the Note about enabling the feautre on this site: [](https://docs.microsoft.com/en-us/ef/core/miscellaneous/connection-resiliency)

> Enabling retry on failure causes EF to internally buffer the resultset, which may significantly increase memory requirements for queries returning large resultsets. See buffering and streaming for more details.
