### ISSUE TITLE
Bug: TimeSeries which are sent on same actorId and documentId are not procssesed

### ISSUE THREAD

**Issue by lasrinnil** [Energinet-DataHub/opengeh-wholesale#210]

**Comment by BjarkeMeier** [comment]
Document IDs are required to be unique for each actor. So this is actually not a bug but due to a missing validation, which should result in an error response. But I don't know if there is yet any project level solution for this or if we're expected to implement our own solution.

**Comment by MadsBloendAndersen** [comment]
@BjarkeMeier We will not be looking at this bug, since it is not part of the current epic we are working on, AND because the architect group is look at a solution on how to perform validations more streamlined throughout the project.
