### ISSUE TITLE
User gets error message in frontend when starting a calculation crossing May 1st. 2023. 

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/opengeh-wholesale#2149]
## Acceptance Criteria

**PROD + PREPROD**

 - [ ] **Scenario 1: User gets an exception when starting a calculation crossing May 1st, 2023**
 
 Given the user is trying to start a calculation that crosses May 1st, 2023
 When the user starts the calculation
 Then the user should get an exception or error message
 
- [ ] **Scenario 2: Exception message is clear and informative**

 Given the user is trying to start a calculation that crosses May 1st, 2023
 When the user starts the calculation
 Then the exception message should clearly state the issue and guide how to resolve it

**DEV + TEST**

 - [ ] **Scenario 1: User gets an exception when starting a calculation crossing Feb. 1st, 2023**
 
 Given the user is trying to start a calculation that crosses Feb. 1st, 2023
 When the user starts the calculation
 Then the user should get an exception or error message
 
- [ ] **Scenario 2: Exception message is clear and informative**

 Given the user is trying to start a calculation that crosses Feb. 1st, 2023
 When the user starts the calculation
 Then the exception message should clearly state the issue and guide how to resolve it

**Comment by BjarkeMeier** [comment]
@MadsBloendAndersen, you never want to ask for exceptions. Exception is a technical term that occurs when something bad happens. What you want here is a proper user experience where the user is informed that it is now allowed - OR the UI simply prevents being able to select dates crossing the cutover date. But those details should probably be decided together with the UI/UX expert (@ManBearTM ).

**Comment by MadsBloendAndersen** [comment]
@ManBearTM 
<img width="1464" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFRUQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8a3012dbb0a0707b79f5fb3263f678f20fa8f26b/image.png" alt="image.png" />

**Comment by MadsBloendAndersen** [comment]
@ManBearTM 

Kan godt se at det faktisk ikke er nævnt på storien, men denne fejl skal faktisk kun gælde for beregningstyperne "Aggregering" og "Balance fiksering"

Dvs. at hvis jeg fx. lavede en engros fiksering eller en korrektions afregning, så skal denne fejl besked ikke komme.

**Comment by ClausQAEnerginet** [comment]
Testet på 
- t-01
- preprod

- Bekræftet at fejlmeddelelsen ikke kommer op til og fra skæringsdatoen 
- Bekræftet af fejlmeddelsen kommer henover skæringsdatoen
