### ISSUE TITLE
Enabler: Improve CI pipeline for better productivity

### ISSUE THREAD

**Issue by BjarkeMeier** [Energinet-DataHub/opengeh-wholesale#244]
Synopsis
=================
As a team
We want a faster and more stable CI pipeline
So that we can be more productive

Acceptance-Criteria
====================
- [ ] The CI pipeline is significantly more stable
- [ ] If viable: The CI pipeline does not execute .NET or Databricks actions when not necessary

The latter AC is very likely to involve team Mighty Ducks.

**Comment by MadsBloendAndersen** [comment]
@mknic and I have decided that MD will look at this issue, since most of the items from @defectiveAi's research, points towards them. MD will contact us, if we need to contribute.
