### ISSUE TITLE
Master data basis data for a balance fixing process is available

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/opengeh-wholesale#280]
## Description 
As a user
i want to prepare master data basis data for a specific process
so that i can compare the expected input to the process with the actual output

## Acceptance criteria
- [ ] Master data basis data are available when a balance fixing process are completed.  
https://app.zenhub.com/files/490590917/33486967-e90a-47f2-b1c0-894a53098321/download

- [ ] Each row in the master data report is distinguished by the following attributes:
![image.png](https://images.zenhubusercontent.com/60bdfcb3effb2082025638c1/fc774176-7497-438a-9145-d7870c5d1b4b)

An example for a master data report:

METERINGPOINTID,VALIDFROM,VALIDTO,GRIDAREAID,TOGRIDAREAID,FROMGRIDAREAID,TYPEOFMP,
SETTLEMENTMETHOD
570667000000000120,2022-08-03T23:00:00Z,2022-08-04T23:00:00Z,667,,,E18

**Comment by lasrinnil** [comment]
I have removed EnergySupplierId from the story after having talked about implementation cost with @MadsBloendAndersen and @khatozen.

**Comment by lasrinnil** [comment]
I have verified the .csv files generated, and conform to the picture in the description. When testing please reach out to me to get the master data csv. files :)
