### ISSUE TITLE
Peek/Dequeue RSM-14 without calculated timeseries values

### ISSUE THREAD

**Issue by lasrinnil** [Energinet-DataHub/opengeh-wholesale#31]
Synopsis
----------------
As an MDR
I want to be able to peek and dequeue an a complete RSM-014 message with no calculated time series values
So that I verify that I am able to receive a complete RSM-014 message with no calculated time series values

RSM-014 example [here](https://energinet.sharepoint.com/:u:/r/sites/DH3ART-team/Delte%20dokumenter/General/CIM/CIM%20XSD%20-%20XML/XML%20filer/XML%2020220425%20-%20Danske%20koder/Notify%20aggregated%20measure%20data_total.xml?csf=1&web=1&e=btczJI).

Acceptance criteria
-----------------
AC 1: We can deliver an RSM-014 with a grid area and a time series for total production (E18) with no calculated values for the points.
AC 2: The time series for total production must be of quarterly resolution (96 entries)

Tasklist
--------------------
- [x] Processmanager 
    - [x] IntegrationTest
- [x] Calculator
    - [x] IntegrationTest
- [x] Sender @lasrinnil @defectiveAi
    - [x] Add BatchId to the completed event
    - [x] IResultsReader which can fetch the files and returns a dto
    - [x] Enrich the DocumentFactory to add the result section based on the dto

**Comment by PerTHenriksen** [comment]
@EnerginetJTI  - could you please provide an example file of a valid RSM-014 CIM /XML for an production aggregation? (just a link to a file in Teams is fine, xml files cannot be attached in zenhub)

**Comment by PerTHenriksen** [comment]
@EnerginetJTI bare for at præcisere; kan du levere en eksempelfil RSM--014 for total production, med de felter som skal indgå, herunder netområde, korrekt type modtager etc. 
Fint hvis du vil lægge et link i denne opgave til teams kanalen hvor eksempelfilen kommer til at bo.
