### ISSUE TITLE
Decide on a strategy for system test

### ISSUE THREAD

**Issue by JesperGomes** [Energinet-DataHub/opengeh-wholesale#336]
### Synopsis
As a team 
we want to ensure that the system still works after we have deployed our software to the shared enviroments
so that we don't slow down others within and outside the team
_____________
### Acceptance Criteria
- [ ] We now what other teams have have already done 
- [ ] We now  what other teams are planning to do
- [ ] We have agreed on a plan with the team
________________
### Tech. Notes
________________

**Comment by MadsBloendAndersen** [comment]
addressed through test guild
