### ISSUE TITLE
Improve testing against our infrastructure and Databricks

### ISSUE THREAD

**Issue by JesperGomes** [Energinet-DataHub/opengeh-wholesale#500]
Synopsis
===============
We are lacking test coverage of the part of our code that relies on Azure resources that we cannot emulate, e.g. Service Bus, Databricks, Event bus, data lakes etc). We need to come with ways to improve test coverage in these areas. It is important that our automated tests are stable and that they don't introduce bottlenecks in our development.

Acceptance-Criteria
================
- [x] concept for integration tests has been settled
- [x] the concept of contract tests (between .NET and Databricks) has been reviewed
- [ ] ~~Testing streaming jobs (integration_events_persister_streaming_job)~~
- [x] a test strategy for databricks functionality has been decided by the development team

- [ ] Ability to unit test and integration test of data lake dependant code.

Tasks
================
- [x] add performance testing section 
- [x] refine Infrastructure testing section @lasrinnil, @BjarkeMeier 
- [x] move strategy to github @JesperGomes 

## Notes
Being able to integrationtest GetAsync on the ProcessStepResultController.
Possibly remove the ServiceCollectionConfigurator containing a mocked DataLakeFileSystemClient
Being able to integration test Data Lake migrations

**Comment by knn-halfspace** [comment]
@rf-halfspace 

FYI - Ability to unit test and integration test of data lake dependant code
