### ISSUE TITLE
Improve Databricks Developer Experience (DX)

### ISSUE THREAD

**Issue by BjarkeMeier** [Energinet-DataHub/opengeh-wholesale#507]
Acceptance Criteria
================
- [x] Good intelli-sense
- [x] Navigation
   - goto declaration
   - find usages
- [x] Code refactorings are supported
   - symbol renaming
   - other?
- [x] Enforce that type hints must be made for parameters in python @johevemi 
   - mypy has been added to the local development environment 
   - Add static type checking to CI story #565
   - Fix mypy errors in tests folder #566
- [x] Add Sonarlint to the container @johevemi

**Comment by knn-halfspace** [comment]
New VS Code extension is in Private Preview
We expect it to be in public preview start Q1
We expect it to bee General Available medium Q2

The plugin / project is called spark connect
https://www.databricks.com/blog/2022/07/07/introducing-spark-connect-the-power-of-apache-spark-everywhere.html

We do beleive that databricks-connect and DBX is no longer of interest

**Comment by knn-halfspace** [comment]
Databricks developer Experience session is planned - Svend and Sebastian is assigned from Halfspace

**Comment by lasrinnil** [comment]
One of the things that changed the experience was switching to Pylint AND rebuilding the container WITHOUT cache.

**Comment by knn-halfspace** [comment]
@lasrinnil @BjarkeMeier @slb-halfspace 

I will share precommit script here 

`repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    - id: check-added-large-files
      args: ['--maxkb=1000']
  - repo: https://github.com/ambv/black
    rev: 22.1.0
    hooks:
    - id: black
      additional_dependencies: ['click==8.0.4']
  - repo: git://github.com/FalconSocial/pre-commit-mirrors-pep257
    rev: 'v0.3.3'
    hooks:
      - id: pep257
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.931
    hooks:
      - id: mypy
        args: [ --disallow-untyped-defs, --disallow-incomplete-defs, --disallow-untyped-calls, --ignore-missing-imports]`

**Comment by BjarkeMeier** [comment]
I got a github.com error, which I resolved with the following command (from [here](https://stackoverflow.com/questions/72486457/fatal-unable-to-connect-to-github-com-github-com0-140-82-121-4-errno-unkno)):
`git config --global url.https://github.com/.insteadOf git://github.com/`
