### ISSUE TITLE
Deployment 

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/opengeh-wholesale#515]
### Description
- we have a terraform "hack" when we deploy to get the streaming job to use the latest deployed package.

30 min. meeting

Acceptance Criteria
====================
- [ ] The wholesale deployment has been reviewed by Halfspace and stories have been created as deemed relevant by the team

**Comment by knn-halfspace** [comment]
@MadsBloendAndersen  Can you describe the issue and the hack - and we will investigate asap
