### ISSUE TITLE
[Mandalorian] Beregn non-profiled forbrug per netområde

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/opengeh-wholesale#525]
### Synopsis
As a DH3 user
I want to view calculated results for non-profiled consumption per grid area
So that I verify that DH3 are calculating non-profiled consumption as expected. 

_____________
### Acceptance Criteria
- [ ] View non profiled consumption per grid areas in frontend
- [ ]  Make results for non-profiled consumption available for EDI domain

**Comment by prtandrup** [comment]
Risks identified:
* Calculating the wrong result (wrong formula or wrong input data, e.g. read table incorrect) - highest risk
* Delivering the wrong results to EDI (endpoint)
* Basis data reports incorrect
* Incorrect results displayed in UI
