### ISSUE TITLE
Python design and architecture review

### ISSUE THREAD

**Issue by lasrinnil** [Energinet-DataHub/opengeh-wholesale#550]
We really need a thorough read trough of our Python code, and a review of the architecture.

A suggestion of action could be could have a hour'ish session with Sebastian from Halfspace.

**Comment by knn-halfspace** [comment]
@Victor Petren Hansen from Halfspace will review Python (Collaboration with Sebastian)

Regarding Spark: @slb-halfspace will review here

Lets have a 15 min kick-off @lasrinnil  when you have time
