### ISSUE TITLE
[Mandalorian] [Enabler] UX for download afregnings rapporter skærmbilledet

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/opengeh-wholesale#586]
### Synopsis
As a user, I want to be able to login to frontend to find the balance fixing processes for a selected period.
So that I can download the settlements report with/without basis data.

The following users must have access to the download screen:
- [x] DataHub Administrator
- [x] Energy Supplier
- [x] Metered Data Responsible

**Comment by mogensjuul** [comment]
@MadsBloendAndersen  er denne egentlig stadig mål fpr epic 1

**Comment by MadsBloendAndersen** [comment]
@mogensjuul jo, jeg lukker den.
