### ISSUE TITLE
Enable DH3 user to start batch for 4 new grid areas (512, 533, 543, 584)

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/opengeh-wholesale#632]
### Synopsis
As a fas user 
i want to start a batch for the following grid areas 512, 533, 543, 584
so that i can start using data from PRE07

### Acceptance criteria
- [x] The list of grid areas in start batch screen has been extended with the following 4 grid areas: 512, 533, 543, 584 ([PR](https://github.com/Energinet-DataHub/greenforce-frontend/pull/1244))
- [ ] When starting a batch for the mentioned grid areas, the batch should fail, since data from PRE07 is not used yet.

**Comment by khatozen** [comment]
Vi må også tilføje netområde 351 til list af netområde for at teste sommer/vintertid skift i 2017.
