### ISSUE TITLE
Architecture guild: Develop C4 diagrams

### ISSUE THREAD

**Issue by BjarkeMeier** [Energinet-DataHub/opengeh-wholesale#639]
The architects wants the team to develop C4 diagrams.

**Comment by BjarkeMeier** [comment]
@Sondergaard , @krmoos can you please provide synopsis and acceptance criteria.

**Comment by BjarkeMeier** [comment]
@MadsBloendAndersen , this issue was requested by the architects. We probably need them to refine the story. I also recommend prioritizing the story when team Volt has made their diagrams.

**Comment by MadsBloendAndersen** [comment]
@BjarkeMeier im aware. I have seen some of the things they have made with those diagrams on level 1 and level 2. I will make sure we will prioritize this, when it make sense.

**Comment by Sondergaard** [comment]
@BjarkeMeier, @MadsBloendAndersen 

We have not asked you to produce any diagrams, only that when you do, that you use the C4 model and Structurizr as a tool.

**Comment by MadsBloendAndersen** [comment]
@Sondergaard @BjarkeMeier What about the diagrams that we have made already - should they be converted to the C4 model? Or maybe they should be converted next time we change them?

**Comment by MadsBloendAndersen** [comment]
@MadsBloendAndersen will delete
