### ISSUE TITLE
Tech: Data Engineering Principles

### ISSUE THREAD

**Issue by lasrinnil** [Energinet-DataHub/opengeh-wholesale#668]
A new manifest was provided by Halfspace shining light on their best practices when working with data engineering.

https://energinet.atlassian.net/wiki/spaces/D3/pages/347144254/Data+Engineering+Principles

Mandalorian team members should read the document and provide a list of subjects to discuss together to plan a course of action to conform to the new best practices and values.

**Comment by johevemi** [comment]
I have created meeting for all six data engineering principles

**Comment by BjarkeMeier** [comment]
Efter aftale med @krmoos  lukker jeg denne story. Hvis der skal ske noget, så kommer der et initiativ fra Spectrum. Kristoffer har bolden.
