### ISSUE TITLE
Persist results / basis data from calculation in Cosmos

### ISSUE THREAD

**Issue by lasrinnil** [Energinet-DataHub/opengeh-wholesale#685]

**Comment by MadsBloendAndersen** [comment]
@lasrinnil what feature does this issue belong to?

**Comment by PerLysemose** [comment]
@MadsBloendAndersen, burde denne ikke være i "refinement"? Ingen beskrivelse, ingen AC´er og ingen estimat :-)

**Comment by MadsBloendAndersen** [comment]
@PerLysemose Jo, jeg rykker den. :)
