### ISSUE TITLE
Provide calculations results to EDI domain

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/opengeh-wholesale#690]
Synopsis
==================
See batmans issue here: 

https://app.zenhub.com/workspaces/batman-60a6105157304f00119be86e/issues/gh/energinet-datahub/geh-market-roles/1521

Acceptance Criteria
========================
- [ ] Solution is accepted by team Batman

Tasks
=====================
- [x] Publish process completed integration event @BjarkeMeier 
- [x] Make HTTP endpoints available to EDI (disable auth temporarily?) @BjarkeMeier 
- [x] Remove all "data available" reminiscences @BjarkeMeier 
- [x] Adjust implementation to suggestion (2) from [here](https://github.com/Energinet-DataHub/opengeh-wholesale/pull/694/files#r1066699948)? @BjarkeMeier 
- [x] Add period to integration event @BjarkeMeier 
- [x] Publish protobuf contract in NuGet package @BjarkeMeier 
- [x] Do not hardcode balance fixing when creating `ProcessCompleted` @BjarkeMeier 
- ~~[ ] Add authentication/authorization as decided by architects @lasrinnil ~~ @BjarkeMeier: Moved to #729
- [x] Extend process manager health check with integration events topic @BjarkeMeier 
- [x] Add quality to results for EDI

- [x] Clean up and add missing tests after PR #706 @BjarkeMeier 
- ~~[ ] Add API documentation~~ @BjarkeMeier: Batman are satisfied with the current doc
- [x] Update existing event flow documentation @BjarkeMeier 
- [x] Fix tests that should check for events based on correlation id. Search for `(_ => true)` @lasrinnil 
- [x] Make `DeserializeByteArrayAsync` DRY and add unit test (found in multiple endpoints) @BjarkeMeier 
- [x] Fix remaining todos @BjarkeMeier 

- [x] Fix that EDI doesn't appear to receive events anymore
- [x] Add period to result (This change is not necessary at this time)

From the architect:

Specifikation for HTTP API – der skal udarbejdes et dokument der beskriver hvordan APIet bruges. Dette kunne være udtrykt som swagger, men er ikke et krav. Ansvarlig - Mandalorian, støttende Batman

Specifikation / kontrakt for integrations event – der skal udarbejdes en beskrivelse af det event der bliver sendt. Dette kunne være som protobuf kontrakt, men er ikke et krav. Ansvarlig – Mandalorian, støttende Batman

Accept af de to specifikationer – det skal vurderes om de nævnte specifikationer dækker behovet for EDI udsendelse. Ansvarlig – Batman, støttende Mandalorian og arkitekter.

Model for Authentication/authorization af HTTP API ved system til system kommunikation – generel beskrivelse der kan anvendes på hele løsningen. Ansvarlig – Arkitekter (KOS, SSG), støttende Mighty Ducks

Når specifikationer / kontrakter er godkendt, kan Batman starte på at implementere disse evt. ved hjælp af mocks. Mandalorian kan starte implementering i Wholesale men må også afvente auth. beskrivelse fra arkitekter.

Arkitekterne levere en beskrivelse af auth i uge 2.

**Comment by BjarkeMeier** [comment]
It has been agreed to address the ADR-107 requirements in a separate story (#729).
According to @kft, we are free to close this story.
