### ISSUE TITLE
Create test data for PRE07

### ISSUE THREAD

**Issue by khatozen** [Energinet-DataHub/opengeh-wholesale#734]
### In scope
A test data for a whole moth must be created, and it must reflect the following changes:
- BRS-001 Change of supplier @khatozen (02/01/2022)
- BRS-002 End of supply @khatozen (04/01/2022)
- BRS-003 incorrect change of supplier (back in time) @khatozen (06/01/2022) 
- BRS-004 create a metering point (status new) @khatozen (08/01/2022)
- BRS-006 update master data (change time resolution) @MadsBloendAndersen (10/01/2022) 
- BRS-007 close down a metering point (status Closed down) @MadsBloendAndersen (12/01/2022) 
- BRS-012 Change of settlement method @MadsBloendAndersen (14/01/2022)
- BRS-013 disconnect and connect a metering point @MadsBloendAndersen (16/01/2022) 

- Indsend timeseries for Januar 2022 @MadsBloendAndersen 
- Indsend timeseries for Marts 2022 + Oktober 2022 @MadsBloendAndersen 

### Out of scope
**Change in Charges:**
Change of master data for charges do not affects the aggregation, except stop charge.
Update the price I DKK for hourly, daily or monthly prices 
It is not allowed to change the time resolution for a charge.

**Change in Charge links:**
- Create a new charge link on a metering point
- Stop a charge link on a metering point
- Update charge links (quantity for Fee/ subscription)
- Charge links exist, the charge is not stopped, but the price is missing.

**Comment by khatozen** [comment]
A test data for a whole moth must be created, and it must reflect the following changes:
- BRS-001 Change of supplier
- BRS-002 End of supply
- BRS-003 incorrect change of supplier (back in time)
- BRS-004 create a metering point (status new)
- BRS-006 update master data (change time resolution)
- BRS-007 close down a metering point (status Closed down)
- BRS-012 Change of settlement method 
- BRS-013 disconnect and connect a metering point

**Change in Charges:**
Change of master data for charges do not affects the aggregation, except stop charge.
Update the price I DKK for hourly, daily or monthly prices 
It is not allowed to change the time resolution for a charge.

**Change in Charge links:**
- Create a new charge link on a metering point
- Stop a charge link on a metering point
- Update charge links (quantity for Fee/ subscription)
- Charge links exist, the charge is not stopped, but the price is missing.

**Comment by PerTHenriksen** [comment]
Test data suite here: 
https://energinet.sharepoint.com/:x:/r/sites/Joules/Delte%20dokumenter/General/PRE07%20data/MeteringPointMasterData_804_PRE07%20(without%20profiled)%20V1.xlsx?d=w214c5fbdc38d4c2ba3c905c3e0384611&csf=1&web=1
