### ISSUE TITLE
Remove batch ID from search batch overview 

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/opengeh-wholesale#765]
### Synopsis
As a DH3 user 
I dont what to see batch-ID on search batch screen 
so that i don't get distracted with information i dont need 

### Acceptance criteria
- [ ] Batch id is removed from search batch overview.

**Comment by MadsBloendAndersen** [comment]
@frontend-specialisten Hvad tænker du om dette opgave? Hvor lang tid tager det at slette den kolonne?

**Comment by frontend-specialisten** [comment]
@MadsBloendAndersen det tager 5min :)

**Comment by MadsBloendAndersen** [comment]
@frontend-specialisten Har du mulighed for at fjerne det i forbindelse med den opgaver du sidder med nu?
