### ISSUE TITLE
Fix roundings 

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/opengeh-wholesale#791]
### Synopsis 
As a business
I want to fix rounding issues when dividing hourly values with 4, to get quarterly values
so that we can calculate exactly the same aggregated timeseries as datahub 2 

### Acceptance criteria
- [x] Rounding issues have been solve using the following method: ![image](https://github.com/Energinet-DataHub/opengeh-wholesale/assets/85936645/b1e5272b-8190-46ce-91eb-fc6dca49760e)

### Example:
An energy supplier has the following 5 flex settled metering points in grid area A:
- 2 MP with time resolution PT15M
- 3 MP with time resolution PT1H
When the calculation is executed for the GA A, then DataHub should calculate the aggregated time series per energy supplier/balance responsible party as following:
1.	Aggregate E17-D01 with PT15M 
2.	Aggregate E17-D01 with PT1H, then divide the result with 4, do rounding to get the values in PT15M.
3.	Add the result from step 2 to step 1, to get only one aggregated time series with time resolution PT15M. 
	
Rounding method:

![image](https://github.com/Energinet-DataHub/opengeh-wholesale/assets/85936645/b1e5272b-8190-46ce-91eb-fc6dca49760e)

Reminder = D - E
Values in column D = C + F

**Comment by khatozen** [comment]
This issue is tested OK, it can be closed.
