### ISSUE TITLE
Create settlement permission and use it in frontend

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/opengeh-wholesale#897]
### Synopsis
As an Energinet settlement administrator
I want to have access to the settlement menu
so that I can start batch, search batch, and download basis data 

### Acceptance criteria
- [ ] User role (Energinet afregnings administrator) with permission(s) to access the settlement menu (3 submenu bullets), is created
- [ ] Only users with permission to access the settlement menu are allowed to start batch, search batch, and download basis data. 
- [ ] Only Energinet users can see the "actor" filter (moved from #691), so we need permission for that as well. 

**Without:**
- [ ] API calls are only available for users with the "energinet afregnings administrator" role.
Note: 
Titans could help with the integration test of permissions.
- [ ] Permissions per role are documented in confluence (PO)

**Tech notes:**
Backend: https://github.com/Energinet-DataHub/geh-core/blob/main/source/App/documents/authorization.md
Frontend: https://github.com/Energinet-DataHub/greenforce-frontend/tree/main/libs/dh/shared/feature-authorization

**Comment by Tm1807** [comment]
@MadsBloendAndersen : Titans tager denne opgave ind nu her.
2 ting I skal levere: 
1) Hvad skal rettigheden hedde?
2) En sigende beskrivelse af hvad rettigheden giver adgang til

Der er egentligt 3 ting, der skal oplyses. Men markedsrollen som rettigheden skal lande i må være:
Markedsrollenavn: DataHub systemadministrator
Markedsrollebeskrivelse: DataHub adgang til drift og support.
