### ISSUE TITLE
Migrate security model from key-based access to IAM

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/opengeh-wholesale#902]
### Synopsis 
Currently Mandalorian uses access key based authorization when connecting to storage accounts from Databricks.

In team Volt's migration solution the identity of a service principal, which has the "storage blob data contributor" role, is used instead of access key.

An explanation of the security model is shown here: https://miro.com/app/board/uXjVP7O-Bkc=/?moveToWidget=3458764540866017907&cot=14

### AC
- [ ] Mandalorian is using IAM 
- [ ] Access keys are not used anywhere in Wholesale

**Comment by JesperGomes** [comment]
Outlaws can test this for us
